DirectoryPath: "_site"
ExternalTimeout: 30
IgnoreDirs:
  - ^docs/stable
  - ^docs/dev
  - ^docs/v1.2
IgnoreURLs:
  - http://localhost:4000
  - "https://github.com.*"
  - "https://movr.cloud"
IgnoreInternalEmptyHash: true
TestFilesConcurrently: true
DocumentConcurrencyLimit: 16
